[project]
name = "apiradar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.3.21",
    "black>=25.12.0",
    "fastapi[standard]>=0.127.1",
    "google-genai>=1.56.0",
    "isort>=7.0.0",
    "openai>=2.14.0",
    "openapi3-parser>=1.1.22",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "ruff>=0.14.10",
    "streamlit>=1.52.2",
    "uvicorn>=0.40.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
